repos:
  # Backend hooks
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--config=backend\.flake8]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  # Frontend hooks
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0 # Check for the latest version
    hooks:
      - id: prettier
