services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: django_backend
    restart: always
    depends_on:
      - db
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

volumes:
  pg_data:
